services:

  api:
    image: tanmaybhatt18/mcp_project-api:latest
    ports:
      - "8000:8000"
    env_file:
    - .env
    volumes:
      - ./backend/agent_workspace:/app/agent_workspace
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    image: tanmaybhatt18/mcp_project-streamlit:latest
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_URL=http://api:8000

